---
title: "practice-functions"
format: html
---

# Setup

```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

```{r}
webpage <- rvest::read_html("https://www.pwrc.usgs.gov/BBL/Bander_Portal/login/speclist.php")

tbls <- rvest::html_nodes(webpage, "table") %>% 
    rvest::html_table(fill = TRUE)

species <- tbls[[1]] %>% # extract first table in list of tables
    janitor::clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))

head(species, 3)
```

```{r}


egg <- read_csv(here("data/Utqiagvik_egg_measurements.csv"),
                show_col_types = FALSE)

nest <- read_csv(here("data/Utqiagvik_nest_data.csv"),
                 show_col_types = FALSE)

pred <- read_csv(here("data/Utqiagvik_predator_surveys.csv"),
                 show_col_types = FALSE)
```

```{r}

pred <- pred %>% 
  left_join(., species, by = c("species" = "alpha_code"))

```

```{r}

assign_spec <- function(table_x, species) {
 left_join(table_x, species, by = c("species" = "alpha_code"))
}

new_pred <- assign_spec(pred, species)

```


